services:
  nutrisage-api:
    build: .
    container_name: nutrisage-api
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DATA_SOURCE=local
      - MODEL_PATH=/app/models/nutrition_grade_model.pkl
      - METADATA_PATH=/app/models/model_metadata.pkl
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./reports:/app/reports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 